### ISSUE TITLE
Possible to create/update via relationship

### ISSUE THREAD

**Issue by samuelcasas** [czim/laravel-nestedupdater#2]
@czim I've seen that is not possible to achieve this:
 
```
$input = $request->all();
$this->user->posts()->create($input);
```

the only way to create/update related models is by injecting directly the user_id to the data on the Post model and accepting the user_id to be mass assignable, the method for creating looks like this:

```
$input = $request->all();
$input['user_id'] = $this->user->id;

$client = Client::create($input);
```

there is any workaround to prevent the creating to do this hacks?

Thanks.

**Comment by czim** [comment]
Hmm. If I understand you correctly, you want to have a way around fillable guards for your models.

So normally you'd do something like:

```php
$client = new Client($request->all());
$client->user_id = $this->user->id;
$client->save();
```

Whereas now, since you're using the nested updater, you can't  inject the `user_id` before saving.

An approach where you could ask the nested model updater to `make()` the model instead of persisting it wouldn't work, since that would break the post-persistence nested relation flow.

So, judging by your PR, your suggested approach would be something like:

```php
$nestedUpdater = new ModelUpdater(YourModelClass::class);

$nestedUpdater->setAttribute('user_id', $this->user->id);
$nestedUpdater->create($request->all());
```

Correct?

If so, this makes sense. Let me think about it a bit further, and then I'll probably accept the PR.
I might change the name to make it clearer that this is an unguarded, 'unsafe' operation, though.
