### ISSUE TITLE
Stuck on nested validator

### ISSUE THREAD

**Issue by michaelw85** [czim/laravel-nestedupdater#7]
Hi,

Not sure if I'm doing something wrong or it's a bug but I can't get the nested validator working as I would like it to.
I tried to get it to work with a company with nested addresses setup: https://github.com/Lecturize/Laravel-Addresses

I'm using classes extending the `FormRequest` class with a `rules` method to define my validation.
So I have a `CompanyRequest` and `AddressRequest` class defining rules.

The following scenario works:
If `CompanyRequest` extends `FormRequest` and `AddressRequest` does not extend anything. 
This setup works but I will lose the ability to easily access data and methods from `FormRequest`.

What fails:
When both extend FormRequest I always get a failure on required attributes. I think the validator is processing the whole request and the nested rules are applied at root level. It also immediately validates nested resources even though I just requested the validation rules. This happens when a new instance I created using `app(AddressRequest::class);`

When I make `AddressRequest` extend `AbstractNestedDataRequest` I get an infinity loop.
I think this might have to do with the full request being processed over and over again which always contains a nested resource.

For all scenario's I created a validator instance, requested the validation rules and input all request data.

Am I missing something? I would assume it should be possible to use classes extending the Form or AbstractNestedDataRequest.

**Comment by czim** [comment]
I can't say I get the full picture. Your description is extensive, but without code I find it difficult to know what's going on and whether it's a bug or not. If you can share the code somewhere, I could getter a better idea and help debug (provided I find the time for it).

**Comment by michaelw85** [comment]
@czim I understand, I can try to setup a clean laravel project to reproduce the issue.
I might be able to provide a repo on Wednesday.

**Comment by michaelw85** [comment]
@czim I've created a repo to reproduce all 3 scenarios: https://github.com/michaelw85/recursive-validation-issue

Created a simple test that should return the nested validation rules:
https://github.com/michaelw85/recursive-validation-issue/blob/master/tests/Feature/ExampleTest.php

You can run the test using `composer run test`;

So 3 scenarios:
1) Current setup will fail with error even when the value is set:
```json
{
    "message": "validation.incorrect_data",
    "errors": {
        "city": [
            "The city field is required."
        ]
    }
}
```
2) If you do not extend `FormRequest` [here](https://github.com/michaelw85/recursive-validation-issue/blob/master/app/Http/Requests/AddressRequest.php#L11)
This will succeed and give the expected validation rules

3) If you extend `AbstractNestedDataRequest` [here](https://github.com/michaelw85/recursive-validation-issue/blob/master/app/Http/Requests/AddressRequest.php#L13)
This will result in an infinite loop error

**Comment by czim** [comment]
I found two issues with your setup that may cause issues:

1. Your `AddressRequest` class returns the wrong value for `getNestedModelClass` (should be `Lecturize\Addresses\Models\Address`, not `App\Models\Company`).
2. You use a FormRequest class as your rules object. This does not work, because instantiating the object causes it to start validating. This is just how the Laravel request validation was designed -- validate on construction, so you can validate by method-injecting FormRequests into controller actions. The NestedValidator instantiates the configured rules classes to retrieve the rules. Since the way you have it set up, this class instance then starts validating _first_, before the NestedValidator can actually retrieve the rules. This in turn starts up a NestedValidator, which needs the rules from the rules class ... ad infinitum.

All you need to do to prevent the infinite recursion loop, I think, is to make separate rule container classes that preferrably don't perform any (validation/recursive) logic when instantiated.

**Comment by michaelw85** [comment]
@czim Sorry for the late reply and thanks for the info! 
1. Ok clear mistake on my side, I thought I had to return the parent so the nested validation could figure out its relation.
2. This is what I also thought, I will have to go back in and see if I can split my setup/drop the FormRequest setup.
